// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "cxxboost",
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "cxxboost",
            targets: ["boost_accumulators","boost_algorithm","boost_align","boost_any","boost_array","boost_asio","boost_assert","boost_assign","boost_atomic","boost_beast","boost_bimap","boost_bind","boost_callable_traits","boost_chrono","boost_circular_buffer","boost_compat","boost_compute","boost_concept_check","boost_config","boost_container","boost_container_hash","boost_context","boost_contract","boost_conversion","boost_convert","boost_core","boost_coroutine","boost_coroutine2","boost_crc","boost_date_time","boost_describe","boost_detail","boost_dll","boost_dynamic_bitset","boost_endian","boost_exception","boost_fiber","boost_filesystem","boost_flyweight","boost_foreach","boost_format","boost_function","boost_function_types","boost_functional","boost_fusion","boost_geometry","boost_gil","boost_graph","boost_graph_parallel","boost_hana","boost_heap","boost_histogram","boost_hof","boost_icl","boost_integer","boost_interprocess","boost_intrusive","boost_io","boost_iostreams","boost_iterator","boost_json","boost_lambda","boost_lambda2","boost_leaf","boost_lexical_cast","boost_local_function","boost_locale","boost_lockfree","boost_log","boost_logic","boost_math","boost_metaparse","boost_move","boost_mp11","boost_mpi","boost_mpl","boost_msm","boost_multi_array","boost_multi_index","boost_multiprecision","boost_mysql","boost_nowide","boost_numeric_conversion","boost_interval","boost_odeint","boost_ublas","boost_optional","boost_outcome","boost_parameter","boost_parameter_python","boost_pfr","boost_phoenix","boost_poly_collection","boost_polygon","boost_pool","boost_predef","boost_preprocessor","boost_process","boost_program_options","boost_property_map","boost_property_map_parallel","boost_property_tree","boost_proto","boost_ptr_container","boost_python","boost_qvm","boost_random","boost_range","boost_ratio","boost_rational","boost_regex","boost_safe_numerics","boost_scope_exit","boost_serialization","boost_signals2","boost_smart_ptr","boost_sort","boost_spirit","boost_stacktrace","boost_statechart","boost_static_assert","boost_static_string","boost_stl_interfaces","boost_system","boost_test","boost_thread","boost_throw_exception","boost_timer","boost_tokenizer","boost_tti","boost_tuple","boost_type_erasure","boost_type_index","boost_type_traits","boost_typeof","boost_units","boost_unordered","boost_url","boost_utility","boost_uuid","boost_variant","boost_variant2","boost_vmd","boost_wave","boost_winapi","boost_xpressive","boost_yap"]),
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(name:"boost_accumulators", path:"boost-libs/accumulators", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_algorithm", path:"boost-libs/algorithm", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_align", path:"boost-libs/align", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_any", path:"boost-libs/any", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_array", path:"boost-libs/array", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_asio", path:"boost-libs/asio", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_assert", path:"boost-libs/assert", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_assign", path:"boost-libs/assign", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_atomic", path:"boost-libs/atomic", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_beast", path:"boost-libs/beast", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_bimap", path:"boost-libs/bimap", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_bind", path:"boost-libs/bind", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_callable_traits", path:"boost-libs/callable_traits", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_chrono", path:"boost-libs/chrono", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_circular_buffer", path:"boost-libs/circular_buffer", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_compat", path:"boost-libs/compat", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_compute", path:"boost-libs/compute", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_concept_check", path:"boost-libs/concept_check", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_config", path:"boost-libs/config", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_container", path:"boost-libs/container", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_container_hash", path:"boost-libs/container_hash", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_context", path:"boost-libs/context", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_contract", path:"boost-libs/contract", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_conversion", path:"boost-libs/conversion", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_convert", path:"boost-libs/convert", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_core", path:"boost-libs/core", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_coroutine", path:"boost-libs/coroutine", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_coroutine2", path:"boost-libs/coroutine2", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_crc", path:"boost-libs/crc", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_date_time", path:"boost-libs/date_time", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_describe", path:"boost-libs/describe", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_detail", path:"boost-libs/detail", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_dll", path:"boost-libs/dll", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_dynamic_bitset", path:"boost-libs/dynamic_bitset", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_endian", path:"boost-libs/endian", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_exception", path:"boost-libs/exception", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_fiber", path:"boost-libs/fiber", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_filesystem", path:"boost-libs/filesystem", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_flyweight", path:"boost-libs/flyweight", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_foreach", path:"boost-libs/foreach", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_format", path:"boost-libs/format", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_function", path:"boost-libs/function", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_function_types", path:"boost-libs/function_types", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_functional", path:"boost-libs/functional", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_fusion", path:"boost-libs/fusion", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_geometry", path:"boost-libs/geometry", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_gil", path:"boost-libs/gil", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_graph", path:"boost-libs/graph", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_graph_parallel", path:"boost-libs/graph_parallel", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_hana", path:"boost-libs/hana", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_heap", path:"boost-libs/heap", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_histogram", path:"boost-libs/histogram", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_hof", path:"boost-libs/hof", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_icl", path:"boost-libs/icl", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_integer", path:"boost-libs/integer", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_interprocess", path:"boost-libs/interprocess", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_intrusive", path:"boost-libs/intrusive", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_io", path:"boost-libs/io", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_iostreams", path:"boost-libs/iostreams", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_iterator", path:"boost-libs/iterator", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_json", path:"boost-libs/json", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_lambda", path:"boost-libs/lambda", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_lambda2", path:"boost-libs/lambda2", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_leaf", path:"boost-libs/leaf", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_lexical_cast", path:"boost-libs/lexical_cast", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_local_function", path:"boost-libs/local_function", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_locale", path:"boost-libs/locale", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_lockfree", path:"boost-libs/lockfree", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_log", path:"boost-libs/log", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_logic", path:"boost-libs/logic", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_math", path:"boost-libs/math", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_metaparse", path:"boost-libs/metaparse", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_move", path:"boost-libs/move", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_mp11", path:"boost-libs/mp11", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_mpi", path:"boost-libs/mpi", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_mpl", path:"boost-libs/mpl", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_msm", path:"boost-libs/msm", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_multi_array", path:"boost-libs/multi_array", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_multi_index", path:"boost-libs/multi_index", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_multiprecision", path:"boost-libs/multiprecision", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_mysql", path:"boost-libs/mysql", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_nowide", path:"boost-libs/nowide", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_numeric_conversion", path:"boost-libs/numeric_conversion", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_interval", path:"boost-libs/interval", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_odeint", path:"boost-libs/odeint", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_ublas", path:"boost-libs/ublas", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_optional", path:"boost-libs/optional", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_outcome", path:"boost-libs/outcome", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_parameter", path:"boost-libs/parameter", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_parameter_python", path:"boost-libs/parameter_python", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_pfr", path:"boost-libs/pfr", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_phoenix", path:"boost-libs/phoenix", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_poly_collection", path:"boost-libs/poly_collection", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_polygon", path:"boost-libs/polygon", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_pool", path:"boost-libs/pool", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_predef", path:"boost-libs/predef", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_preprocessor", path:"boost-libs/preprocessor", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_process", path:"boost-libs/process", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_program_options", path:"boost-libs/program_options", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_property_map", path:"boost-libs/property_map", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_property_map_parallel", path:"boost-libs/property_map_parallel", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_property_tree", path:"boost-libs/property_tree", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_proto", path:"boost-libs/proto", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_ptr_container", path:"boost-libs/ptr_container", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_python", path:"boost-libs/python", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_qvm", path:"boost-libs/qvm", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_random", path:"boost-libs/random", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_range", path:"boost-libs/range", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_ratio", path:"boost-libs/ratio", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_rational", path:"boost-libs/rational", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_regex", path:"boost-libs/regex", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_safe_numerics", path:"boost-libs/safe_numerics", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_scope_exit", path:"boost-libs/scope_exit", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_serialization", path:"boost-libs/serialization", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_signals2", path:"boost-libs/signals2", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_smart_ptr", path:"boost-libs/smart_ptr", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_sort", path:"boost-libs/sort", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_spirit", path:"boost-libs/spirit", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_stacktrace", path:"boost-libs/stacktrace", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_statechart", path:"boost-libs/statechart", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_static_assert", path:"boost-libs/static_assert", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_static_string", path:"boost-libs/static_string", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_stl_interfaces", path:"boost-libs/stl_interfaces", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_system", path:"boost-libs/system", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_test", path:"boost-libs/test", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_thread", path:"boost-libs/thread", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_throw_exception", path:"boost-libs/throw_exception", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_timer", path:"boost-libs/timer", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_tokenizer", path:"boost-libs/tokenizer", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_tti", path:"boost-libs/tti", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_tuple", path:"boost-libs/tuple", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_type_erasure", path:"boost-libs/type_erasure", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_type_index", path:"boost-libs/type_index", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_type_traits", path:"boost-libs/type_traits", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_typeof", path:"boost-libs/typeof", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_units", path:"boost-libs/units", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_unordered", path:"boost-libs/unordered", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_url", path:"boost-libs/url", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_utility", path:"boost-libs/utility", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_uuid", path:"boost-libs/uuid", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_variant", path:"boost-libs/variant", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_variant2", path:"boost-libs/variant2", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_vmd", path:"boost-libs/vmd", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_wave", path:"boost-libs/wave", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_winapi", path:"boost-libs/winapi", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_xpressive", path:"boost-libs/xpressive", sources:[], publicHeadersPath:"include", packageAccess:true),
		.target(name:"boost_yap", path:"boost-libs/yap", sources:[], publicHeadersPath:"include", packageAccess:true)
    ]
)
